/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import javax.swing.JOptionPane;

/**
 *
 * @author JonnathanE
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Banco bn = new Banco();

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearCuenta = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        comboBox1 = new javax.swing.JComboBox<>();
        btnCancelarCrearCuenta = new javax.swing.JButton();
        JDCrearAhorro = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBalanceAhorro = new javax.swing.JTextField();
        txtInteresesAhorro = new javax.swing.JTextField();
        btnAceptarCrearAhorro = new javax.swing.JButton();
        btnCancelarCrearAhorro = new javax.swing.JButton();
        JDCrearPrestamo = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        txtBalancePrestamo = new javax.swing.JTextField();
        txtInteresesPrestamo = new javax.swing.JTextField();
        btnAceptarCrearPrestamo = new javax.swing.JButton();
        btnCancelarCrearPrestamo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JDCrearIpoteca = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBalanceHipoteca = new javax.swing.JTextField();
        txtInteresesHipoteca = new javax.swing.JTextField();
        btnAceptarCrearHipoteca = new javax.swing.JButton();
        btnCancelarCrearHipoteca = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDepositosHipoteca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMesesHipoteca = new javax.swing.JTextField();
        Depositar = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        comboBoxDepositar = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnCancelarDepositar = new javax.swing.JButton();
        btnCrearCuanta = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        jLabel1.setText("Cliente");

        jLabel2.setText("Tipo de Cuenta");

        comboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Cuenta Ahorro", "Cuenta Prestamo", "Cuenta Hipoteca" }));
        comboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox1ActionPerformed(evt);
            }
        });

        btnCancelarCrearCuenta.setText("Cancelar");
        btnCancelarCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearCuentaLayout = new javax.swing.GroupLayout(CrearCuenta.getContentPane());
        CrearCuenta.getContentPane().setLayout(CrearCuentaLayout);
        CrearCuentaLayout.setHorizontalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnCancelarCrearCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrearCuentaLayout.setVerticalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnCancelarCrearCuenta)
                .addGap(58, 58, 58))
        );

        jLabel3.setText("Balance");

        jLabel4.setText("Tasa de Intereses");

        btnAceptarCrearAhorro.setText("Aceptar");
        btnAceptarCrearAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCrearAhorroActionPerformed(evt);
            }
        });

        btnCancelarCrearAhorro.setText("Cancelar");
        btnCancelarCrearAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearAhorroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JDCrearAhorroLayout = new javax.swing.GroupLayout(JDCrearAhorro.getContentPane());
        JDCrearAhorro.getContentPane().setLayout(JDCrearAhorroLayout);
        JDCrearAhorroLayout.setHorizontalGroup(
            JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDCrearAhorroLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDCrearAhorroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(101, 101, 101)
                        .addComponent(txtBalanceAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JDCrearAhorroLayout.createSequentialGroup()
                        .addGroup(JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAceptarCrearAhorro)
                            .addComponent(jLabel4))
                        .addGap(51, 51, 51)
                        .addGroup(JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInteresesAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarCrearAhorro))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        JDCrearAhorroLayout.setVerticalGroup(
            JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDCrearAhorroLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBalanceAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInteresesAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(JDCrearAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCrearAhorro)
                    .addComponent(btnCancelarCrearAhorro))
                .addGap(47, 47, 47))
        );

        jLabel5.setText("Tasa de Intereses");

        btnAceptarCrearPrestamo.setText("Aceptar");
        btnAceptarCrearPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCrearPrestamoActionPerformed(evt);
            }
        });

        btnCancelarCrearPrestamo.setText("Cancelar");
        btnCancelarCrearPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearPrestamoActionPerformed(evt);
            }
        });

        jLabel6.setText("Balance");

        javax.swing.GroupLayout JDCrearPrestamoLayout = new javax.swing.GroupLayout(JDCrearPrestamo.getContentPane());
        JDCrearPrestamo.getContentPane().setLayout(JDCrearPrestamoLayout);
        JDCrearPrestamoLayout.setHorizontalGroup(
            JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDCrearPrestamoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDCrearPrestamoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(101, 101, 101)
                        .addComponent(txtBalancePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JDCrearPrestamoLayout.createSequentialGroup()
                        .addGroup(JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAceptarCrearPrestamo)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInteresesPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarCrearPrestamo))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        JDCrearPrestamoLayout.setVerticalGroup(
            JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDCrearPrestamoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBalancePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInteresesPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(JDCrearPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCrearPrestamo)
                    .addComponent(btnCancelarCrearPrestamo))
                .addGap(47, 47, 47))
        );

        jLabel7.setText("Balance");

        jLabel8.setText("Tasa de Intereses");

        btnAceptarCrearHipoteca.setText("Aceptar");
        btnAceptarCrearHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCrearHipotecaActionPerformed(evt);
            }
        });

        btnCancelarCrearHipoteca.setText("Cancelar");
        btnCancelarCrearHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCrearHipotecaActionPerformed(evt);
            }
        });

        jLabel9.setText("Depositos");

        jLabel10.setText("Meses");

        javax.swing.GroupLayout JDCrearIpotecaLayout = new javax.swing.GroupLayout(JDCrearIpoteca.getContentPane());
        JDCrearIpoteca.getContentPane().setLayout(JDCrearIpotecaLayout);
        JDCrearIpotecaLayout.setHorizontalGroup(
            JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDCrearIpotecaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDCrearIpotecaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(101, 101, 101)
                        .addComponent(txtBalanceHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JDCrearIpotecaLayout.createSequentialGroup()
                        .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAceptarCrearHipoteca)
                                .addComponent(jLabel8))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(51, 51, 51)
                        .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInteresesHipoteca, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(btnCancelarCrearHipoteca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDepositosHipoteca)
                            .addComponent(txtMesesHipoteca))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        JDCrearIpotecaLayout.setVerticalGroup(
            JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDCrearIpotecaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBalanceHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInteresesHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(45, 45, 45)
                .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtDepositosHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtMesesHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(JDCrearIpotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCrearHipoteca)
                    .addComponent(btnCancelarCrearHipoteca))
                .addGap(47, 47, 47))
        );

        jLabel11.setText("Tipo de cuenta");

        comboBoxDepositar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Cuenta Ahorro", "Cuenta Prestamo", "Cuenta Hipoteca" }));
        comboBoxDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepositarActionPerformed(evt);
            }
        });

        jLabel12.setText("DEPOSITAR");

        btnCancelarDepositar.setText("Cancelar");
        btnCancelarDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDepositarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DepositarLayout = new javax.swing.GroupLayout(Depositar.getContentPane());
        Depositar.getContentPane().setLayout(DepositarLayout);
        DepositarLayout.setHorizontalGroup(
            DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(DepositarLayout.createSequentialGroup()
                .addGroup(DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel11)
                        .addGap(81, 81, 81)
                        .addComponent(comboBoxDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DepositarLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnCancelarDepositar)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        DepositarLayout.setVerticalGroup(
            DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepositarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(DepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnCancelarDepositar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearCuanta.setText("Crear Cuenta");
        btnCrearCuanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuantaActionPerformed(evt);
            }
        });

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnRetirar)
                    .addComponent(btnDepositar)
                    .addComponent(btnCrearCuanta))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnCrearCuanta)
                .addGap(48, 48, 48)
                .addComponent(btnDepositar)
                .addGap(38, 38, 38)
                .addComponent(btnRetirar)
                .addGap(48, 48, 48)
                .addComponent(btnGuardar)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuantaActionPerformed
        CrearCuenta.setSize(this.getSize());
        CrearCuenta.setVisible(true);
        dispose();
        txtCliente.setText("");
        txtBalanceAhorro.setText("");
        txtInteresesAhorro.setText("");
        txtBalancePrestamo.setText("");
        txtInteresesPrestamo.setText("");
        txtBalanceHipoteca.setText("");
        txtInteresesHipoteca.setText("");
    }//GEN-LAST:event_btnCrearCuantaActionPerformed

    private void comboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox1ActionPerformed
        switch (comboBox1.getSelectedIndex()) {
            case 1:
                JDCrearAhorro.setSize(this.getSize());
                JDCrearAhorro.setVisible(true);
                break;
            case 2:
                JDCrearPrestamo.setSize(this.getSize());
                JDCrearPrestamo.setVisible(true);
                break;
            case 3:
                JDCrearIpoteca.setSize(this.getSize());
                JDCrearIpoteca.setVisible(true);
                break;
        }
    }//GEN-LAST:event_comboBox1ActionPerformed

    private void btnCancelarCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearCuentaActionPerformed
        this.setVisible(true);
        CrearCuenta.setVisible(false);
    }//GEN-LAST:event_btnCancelarCrearCuentaActionPerformed

    private void btnAceptarCrearAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCrearAhorroActionPerformed

        CuentaAhorro ca = new CuentaAhorro(txtCliente.getText());
        ca.setTipoCliente("Cuenta Ahorro");
        ca.setBalance(Double.parseDouble(txtBalanceAhorro.getText()));
        ca.setTasaInteres(Double.parseDouble(txtInteresesAhorro.getText()));
        bn.agregar(ca);
        dispose();
        this.setVisible(true);
        CrearCuenta.setVisible(false);
    }//GEN-LAST:event_btnAceptarCrearAhorroActionPerformed

    private void btnCancelarCrearAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearAhorroActionPerformed
        JDCrearAhorro.dispose();
    }//GEN-LAST:event_btnCancelarCrearAhorroActionPerformed

    private void btnAceptarCrearPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCrearPrestamoActionPerformed

        CuentaPrestamo cp = new CuentaPrestamo(txtCliente.getText());
        cp.setTipoCliente("Cuenta Prestamo");
        cp.setBalance(Double.parseDouble(txtBalancePrestamo.getText()));
        cp.setTasaInteres(Double.parseDouble(txtInteresesPrestamo.getText()));
        bn.agregar(cp);
        dispose();
        this.setVisible(true);
        CrearCuenta.setVisible(false);
    }//GEN-LAST:event_btnAceptarCrearPrestamoActionPerformed

    private void btnCancelarCrearPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearPrestamoActionPerformed
        JDCrearPrestamo.dispose();
    }//GEN-LAST:event_btnCancelarCrearPrestamoActionPerformed

    private void btnAceptarCrearHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCrearHipotecaActionPerformed
        CuentaHipoteca ch = new CuentaHipoteca(txtCliente.getText());
        ch.setTipoCliente("Cuenta Hipoteca");
        ch.setBalance(Double.parseDouble(txtBalanceHipoteca.getText()));
        ch.setTasaInteres(Double.parseDouble(txtInteresesHipoteca.getText()));
        ch.depositos = Integer.parseInt(txtDepositosHipoteca.getText());
        ch.meses = Integer.parseInt(txtMesesHipoteca.getText());
        bn.agregar(ch);
        dispose();
        this.setVisible(true);
        CrearCuenta.setVisible(false);
    }//GEN-LAST:event_btnAceptarCrearHipotecaActionPerformed

    private void btnCancelarCrearHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearHipotecaActionPerformed
        JDCrearIpoteca.dispose();
    }//GEN-LAST:event_btnCancelarCrearHipotecaActionPerformed

    private void comboBoxDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepositarActionPerformed
        switch (comboBoxDepositar.getSelectedIndex()) {
            case 1:
                Cuenta c = bn.buscarCuentaAhorro();
                if(c!= null){
                c.depositar(Double.parseDouble(JOptionPane.showInputDialog(null, "Monto")));
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro el nombre");
                }
                break;
            case 2:
                Cuenta cp = bn.buscarCuentaPrestamo();
                if(cp != null){
                cp.depositar(Double.parseDouble(JOptionPane.showInputDialog(null, "Monto")));
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro el nombre");
                }
                break;
            case 3:
                Cuenta ch = bn.buscarCuentaHipoteca();
                if(ch != null){
                ch.depositar(Double.parseDouble(JOptionPane.showInputDialog(null, "Monto")));
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro el nombre");
                }
                break;
        }

    }//GEN-LAST:event_comboBoxDepositarActionPerformed

    private void btnCancelarDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDepositarActionPerformed
        Depositar.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnCancelarDepositarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        Depositar.setSize(this.getSize());
        Depositar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        Cuenta c = bn.buscarCuentaAhorro();
        if(c != null){
            CuentaAhorro ca = (CuentaAhorro)c;
            ca.retirar(Double.parseDouble(JOptionPane.showInputDialog(null,"Monto")));
        }else{
            JOptionPane.showMessageDialog(null, "No se encontro el nombre");
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        bn.grabar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CrearCuenta;
    private javax.swing.JFrame Depositar;
    private javax.swing.JDialog JDCrearAhorro;
    private javax.swing.JDialog JDCrearIpoteca;
    private javax.swing.JDialog JDCrearPrestamo;
    private javax.swing.JButton btnAceptarCrearAhorro;
    private javax.swing.JButton btnAceptarCrearHipoteca;
    private javax.swing.JButton btnAceptarCrearPrestamo;
    private javax.swing.JButton btnCancelarCrearAhorro;
    private javax.swing.JButton btnCancelarCrearCuenta;
    private javax.swing.JButton btnCancelarCrearHipoteca;
    private javax.swing.JButton btnCancelarCrearPrestamo;
    private javax.swing.JButton btnCancelarDepositar;
    private javax.swing.JButton btnCrearCuanta;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JComboBox<String> comboBox1;
    private javax.swing.JComboBox<String> comboBoxDepositar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBalanceAhorro;
    private javax.swing.JTextField txtBalanceHipoteca;
    private javax.swing.JTextField txtBalancePrestamo;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDepositosHipoteca;
    private javax.swing.JTextField txtInteresesAhorro;
    private javax.swing.JTextField txtInteresesHipoteca;
    private javax.swing.JTextField txtInteresesPrestamo;
    private javax.swing.JTextField txtMesesHipoteca;
    // End of variables declaration//GEN-END:variables
}
